services:
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOTNET_PORT}:80"
    volumes:
      - .:/app
      - ../../logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    external: true
