services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    command: "postgres"

  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app-network
    depends_on:
      - postgres
    command: "migrate"
    entrypoint: ["migrate"]
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}?sslmode=disable"
    volumes:
      - ./migrations:/app/migrations

networks:
  app-network:
    external: true
