services:
  nest-db:
    image: postgres:latest
    container_name: nest-db
    environment:
      POSTGRES_USER: ${NEST_DB_USER}
      POSTGRES_PASSWORD: ${NEST_DB_PASSWORD}
      POSTGRES_DB: ${NEST_DB_NAME}
    ports:
      - "${NEST_DB_PORT}:5432"
    volumes:
      - nest_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: "postgres"
    
  python-db:
    image: postgres:latest
    container_name: python-db
    environment:
      POSTGRES_USER: ${PYTHON_DB_USER}
      POSTGRES_PASSWORD: ${PYTHON_DB_PASSWORD}
      POSTGRES_DB: ${PYTHON_DB_NAME}
    ports:
      - "${PYTHON_DB_PORT}:5432"
    volumes:
      - python_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: "postgres"
    
  dotnet-db:
    image: postgres:latest
    container_name: dotnet-db
    environment:
      POSTGRES_USER: ${DOTNET_DB_USER}
      POSTGRES_PASSWORD: ${DOTNET_DB_PASSWORD}
      POSTGRES_DB: ${DOTNET_DB_NAME}
    ports:
      - "${DOTNET_DB_PORT}:5432"
    volumes:
      - dotnet_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: "postgres"

  shared-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SHARED_DB_USER}
      POSTGRES_PASSWORD: ${SHARED_DB_PASSWORD}
      POSTGRES_DB: ${SHARED_DB_NAME}
    ports:
      - "${SHARED_DB_PORT}:5432"
    networks:
      - app-network
    volumes:
      - shared_db_data:/var/lib/postgresql/data
    command: "postgres"

  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app-network
    depends_on:
      - shared-db
    command: "migrate"
    entrypoint: ["migrate"]
    environment:
      DATABASE_URL: "postgres://${SHARED_DB_USER}:${SHARED_DB_PASSWORD}@localhost:${SHARED_DB_PORT}/${SHARED_DB_NAME}?sslmode=disable"
    volumes:
      - ./migrations:/app/migrations

volumes:
  nest_db_data:
  python_db_data:
  dotnet_db_data:
  shared_db_data:

networks:
  app-network:
    external: true
