services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NEST_PORT}:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ../../logs:/usr/src/app/logs
    networks:
      - app-network
    env_file:
      - ../../.env

networks:
  app-network:
    external: true
