services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - "GRAFANA_PORT=${GRAFANA_PORT}"
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - ./loki_data:/loki
    ports:
      - "${LOKI_PORT}:3100"
    environment:
      - "LOKI_PORT=4100"
    restart: always
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./../../logs:/app/logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    ports:
      - "${PROMTAIL_PORT}:4200"
    networks:
      - app-network

volumes:
  grafana-storage:

networks:
  app-network:
    external: true
